# Generated by Django 3.2.8 on 2021-10-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userRole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Roles', to='login.role'),
        ),
    ]
